### ISSUE TITLE
main export in package.json is incorrect

### ISSUE THREAD

**Issue by GlenAttwell** [mobily-enterprises/ejs4b#1]
I installed the package to my solution using npm:
`npm i ejs4b`

I got an error trying to import the module like an es6 module:
"Failed to resolve entry for package "ejs4b". The package may have incorrect main/module/exports specified in its package.json."

My import:
`import ejs from "ejs4b";`

I also tried the following but got an error:
import ejs from "ejs4b/ejs-es";

To fix the issue I had to change my import to the specific default ES6 file:
`import ejs from "../../../../node_modules/ejs4b/ejs-es";`

**Comment by mercmobily** [comment]
Can you give me a link to your repo, or a link to a minimal repo that
reproduces this?

**Comment by GlenAttwell** [comment]
Hey Tony, I can share a codesandbox with you
https://codesandbox.io/s/ejs4b-example-vysz7n

I've added two imports to a vanilla JS sandbox.

**Comment by mercmobily** [comment]
I will never apologise enough for the delay.
I am sorry. I  had archived this email by accident -- it never happens...

What I do is this:

```
import ejs from 'ejs4b/ejs-es.js'
```

Please reopen if it doesn't work.
Sorry again.
